package dev.iskyd.dok2.data.db

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/** Data-access for the `tracks` table. */
@Dao
interface TrackDao {

    /** Inserts a track and returns its autogenerated id. */
    @Insert suspend fun insert(track: TrackEntity): Long

    /** Updates an existing track, matched by primary key. */
    @Update suspend fun update(track: TrackEntity)

    /** Deletes the given track row. */
    @Delete suspend fun delete(track: TrackEntity)

    /** Loads one track by id, or null when it does not exist. */
    @Query("SELECT * FROM tracks WHERE id = :id") suspend fun getById(id: Long): TrackEntity?

    /**
     * Emits the track-list summary projection, newest first. The projection is deliberately limited
     * to the columns the track list renders so `notes` and `thumbnail_path` payloads are never read
     * for the list.
     */
    @Query(
        "SELECT id, name, started_at AS startedAtMs, distance_m AS distanceM, " +
            "elapsed_time_s AS elapsedTimeS, gain_dem_m AS gainDemM " +
            "FROM tracks ORDER BY started_at DESC"
    )
    fun observeSummaries(): Flow<List<TrackSummaryRow>>

    /** Emits all tracks, newest first. */
    @Query("SELECT * FROM tracks ORDER BY started_at DESC")
    fun observeAll(): Flow<List<TrackEntity>>

    /**
     * The single track that was never finalised (`ended_at IS NULL`), if any. The service resumes
     * recording into it after a reboot; the UI prompts to resume or finalise it on launch
     * (DOCUMENTATION.md §Known device problems, mitigation 5).
     */
    @Query("SELECT * FROM tracks WHERE ended_at IS NULL ORDER BY started_at DESC LIMIT 1")
    suspend fun getOpenTrack(): TrackEntity?
}
