package dev.iskyd.dok2.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import kotlinx.coroutines.flow.Flow

/** Data-access for the `trackpoints` table. */
@Dao
interface TrackPointDao {

    /**
     * Inserts a batch of points in a single transaction. The caller batches roughly every 10 points
     * (30 s of recording) so a process kill costs at most 30 seconds of points.
     */
    @Transaction @Insert suspend fun insertAll(points: List<TrackPointEntity>)

    /** Loads all points of a track in recording order. */
    @Query("SELECT * FROM trackpoints WHERE track_id = :trackId ORDER BY seq")
    suspend fun getByTrack(trackId: Long): List<TrackPointEntity>

    /**
     * Emits all points of a track in recording order, re-emitting whenever the stored points
     * change. The live map observes this to grow the polyline while recording.
     */
    @Query("SELECT * FROM trackpoints WHERE track_id = :trackId ORDER BY seq")
    fun observeByTrack(trackId: Long): Flow<List<TrackPointEntity>>

    /**
     * The highest `seq` stored for a track, or -1 when the track has no points yet. The caller uses
     * this to assign the next `seq`: the composite primary key means seq is never autogenerated by
     * the database.
     */
    @Query("SELECT COALESCE(MAX(seq), -1) FROM trackpoints WHERE track_id = :trackId")
    suspend fun maxSeq(trackId: Long): Long

    /**
     * Writes the DEM-derived altitude for one point. [altDemM] is a derived value computed at
     * track-save time (DOCUMENTATION.md §Elevation — Final); raw columns are never touched.
     */
    @Query("UPDATE trackpoints SET alt_dem_m = :altDemM WHERE track_id = :trackId AND seq = :seq")
    suspend fun updateAltDem(trackId: Long, seq: Long, altDemM: Double?)

    /**
     * The lowest and highest altitude of a track from both sources. DEM altitude is the display
     * source of truth per DOCUMENTATION.md §Elevation; raw GNSS is kept as the fallback. MIN/MAX
     * ignore NULLs, so both columns of a pair are non-null iff the track has at least one point
     * with that altitude.
     */
    @Query(
        "SELECT MIN(alt_dem_m) AS minDemM, MAX(alt_dem_m) AS maxDemM, " +
            "MIN(alt_gnss_m) AS minGnssM, MAX(alt_gnss_m) AS maxGnssM " +
            "FROM trackpoints WHERE track_id = :trackId"
    )
    suspend fun getAltitudeExtremes(trackId: Long): AltitudeExtremesRow

    /** Deletes every point of a track. */
    @Query("DELETE FROM trackpoints WHERE track_id = :trackId")
    suspend fun deleteByTrack(trackId: Long)
}
