package dev.iskyd.dok2.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index

/**
 * A single stored point of a track, mirroring the `trackpoints` table from DOCUMENTATION.md §Data
 * model.
 *
 * DOCUMENTATION.md declares this table `WITHOUT ROWID`; Room cannot express that, so the table has
 * an ordinary rowid. The domain contract is preserved: the composite primary key (track_id, seq) is
 * enforced and [seq] is generated by the recording service, never by the database — there is no
 * autoincrement.
 *
 * Raw sensor values ([altGnssM], [pressureHpa]) are stored verbatim and never overwritten; derived
 * figures such as [altDemM] live in their own columns.
 */
@Entity(tableName = "trackpoints", primaryKeys = ["track_id", "seq"], indices = [Index("track_id")])
data class TrackPointEntity(
    @ColumnInfo(name = "track_id") val trackId: Long,
    val seq: Long,
    @ColumnInfo(name = "t_ms") val tMs: Long,
    @ColumnInfo(name = "lat_e7") val latE7: Int,
    @ColumnInfo(name = "lon_e7") val lonE7: Int,
    @ColumnInfo(name = "accuracy_m") val accuracyM: Double,
    @ColumnInfo(name = "alt_gnss_m") val altGnssM: Double? = null,
    @ColumnInfo(name = "alt_dem_m") val altDemM: Double? = null,
    @ColumnInfo(name = "pressure_hpa") val pressureHpa: Double? = null,
    @ColumnInfo(name = "speed_mps") val speedMps: Double? = null,
    @ColumnInfo(name = "bearing_deg") val bearingDeg: Double? = null,
    val state: Int,
    val accumulated: Boolean,
)
