package dev.iskyd.dok2.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query

/** Data-access for the `waypoints` table. */
@Dao
interface WaypointDao {

    /** Inserts a waypoint and returns its autogenerated id. */
    @Insert suspend fun insert(waypoint: WaypointEntity): Long

    /** Loads the waypoints of a track in chronological order. */
    @Query("SELECT * FROM waypoints WHERE track_id = :trackId ORDER BY t_ms")
    suspend fun getByTrack(trackId: Long): List<WaypointEntity>

    /** Deletes every waypoint of a track. */
    @Query("DELETE FROM waypoints WHERE track_id = :trackId")
    suspend fun deleteByTrack(trackId: Long)
}
